extends:
  - airbnb

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true
  es6: true

settings:
  react:
    version: latest
  import/resolver:
    - node
    - webpack

rules:
  no-console: 0
  linebreak-style: ['error', 'windows']
  semi: 0
  comma-dangle: 0
